### PR TITLE
Dependencies update and minor enhancements

### PR DESCRIPTION
**Pull request by ricardomomm**
- Updated dependencies
- Moved the trashcan to the bottom of the page, look more friendly
- Made some enhancement in drag x click detection
  bottom trashcan

### CODE REVIEW

**Comment by oazabir** [comment]
Awesome work! Could you remove the console.log commands please? IE breaks on that.

**Comment by ricardomomm** [comment]
For sure, I will remove it, can I give you a suggestion? Remove Visual Studio/ASP.Net dependency, make this only a html5 application, it will be more "clean", I can help with that.

**Comment by oazabir** [comment]
Sure, let's do it. 

I had to use ASP.NET to put the sign up feature. Is there any way to offer the signup login feature without having any server side technology?

**Comment by ricardomomm** [comment]
Understood your needs so I will do a better explanation of my suggestion,
tell me what you think:

Keep Droptiles only as a html+js+css+assets project, you could control your
dependencies using bower or node, and later create a package for this,
increasing the adoption of this "tile framework" independent of server
technology, will be better for other people to update Droptiles later. You
could keep that ASP.NET part but provide it as a sample usage inside
another directory (\samples\aspnet).

Answering your "signup login feature" question, you could keep this as
simple requests, if I want to, I could develop a OAuth integration and
throw away your Asp.net signup feature. You should provide a sample but
isn't Droptiles responsibility to control login\signup.

But is up to you, it's only a suggestion, I could help if you want.

[]´s

Ricardo Momm

2015-02-13 5:57 GMT-02:00 Omar AL Zabir notifications@github.com:

**Comment by oazabir** [comment]
That sounds like a very good suggestion. Please let me know how we should start.

**Pull request merged**
